name: adv-ml-swa_g
channels:
  - defaults
dependencies:
  - python=3.6  # Google Colab is on Python 3.6
  - pip
  - pip:
    - pip-tools

optional:
  - cudatoolkit=10.1 [--no-deps] # if on osx 
  - cudnn=7.6 [-- no-deps] # if on osx
